services:
  app:
    image: almuko/ddl-app:latest
    container_name: ddl_app
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ddl_storage:/var/www/storage
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: ddl_web
    ports:
      - "8081:80"
    volumes:      
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:17
    container_name: ddl_db
    environment:
      POSTGRES_DB: ddl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zxcvbnm123
    volumes:
      - ddl_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  ddl_storage:
  ddl_pgdata:
