services:
  app:
    image: almuko/ddl-app:latest
    container_name: ddl_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: ddl_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www              # üî• –í–û–¢ –≠–¢–û–ì–û –ù–ï –•–í–ê–¢–ê–õ–û
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:17
    container_name: ddl_db
    environment:
      POSTGRES_DB: ddl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zxcvbnm123
    volumes:
      - ddl_pgdata:/var/lib/postgresql/data

volumes:
  ddl_pgdata:

